### PR TITLE
Fix file parsing for Eve v19

### LINKED ISSUE #183: Chatlog Filename Change
As of todays update, the format of the chatlogs have changed with an additional ID after the date/time stamp.
I suspect this to be the reason, why Vintel is not getting intel chat messages and the current system.

### PR DESCRIPTION
**Pull request by jblemee**
Fix https://github.com/Xanthos-Code/vintel/issues/183

### CODE REVIEW

**Comment by alphagreek** [comment]
I would like to ask for help from someone who has the necessary knowledge to create a new exe file with the new code with the help of PyInstaller

**Comment by jblemee** [comment]
> I would like to ask for help from someone who has the necessary knowledge to create a new exe file with the new code with the help of PyInstaller

I've put the exe here : https://github.com/jblemee/vintel/releases

**Comment by alphagreek** [comment]
Thank you very much for the prompt response.
________________________________
Από: Jean-Baptiste Lemée <notifications@github.com>
Στάλθηκε: Πέμπτη, 11 Φεβρουαρίου 2021 12:40 μμ
Προς: Xanthos-Code/vintel <vintel@noreply.github.com>
Κοιν.: alphagreek <plizos@hotmail.com>; Comment <comment@noreply.github.com>
Θέμα: Re: [Xanthos-Code/vintel] Fix file parsing for Eve v19 (#184)


I would like to ask for help from someone who has the necessary knowledge to create a new exe file with the new code with the help of PyInstaller

I've put the exe here : https://github.com/jblemee/vintel/releases

**Comment by alphagreek** [comment]
When I'm trying to install i get this wrong message.

I have windows 8.1


Do you have a suggestion?

________________________________
Από: Jean-Baptiste Lemée <notifications@github.com>
Στάλθηκε: Πέμπτη, 11 Φεβρουαρίου 2021 12:40 μμ
Προς: Xanthos-Code/vintel <vintel@noreply.github.com>
Κοιν.: alphagreek <plizos@hotmail.com>; Comment <comment@noreply.github.com>
Θέμα: Re: [Xanthos-Code/vintel] Fix file parsing for Eve v19 (#184)


I would like to ask for help from someone who has the necessary knowledge to create a new exe file with the new code with the help of PyInstaller

I've put the exe here : https://github.com/jblemee/vintel/releases

**Comment by jblemee** [comment]
I don't see your error message, please use the github interface instead of replying to the notification email

**Comment by alphagreek** [comment]
I'm using windows 8.1 and I get the next Error Message:  "This windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above). 
So far I have been using successfully this version https://github.com/Xanthos-Code/vintel/releases (1.2.3) 
whose exe file size is 25.4 mb and I wonder if it is possible to change the code in this version
Χωρίς τίτλο

**Comment by Eingang** [comment]
I appreciate that there's a Mac version! I've been using 1.2.3 for ages. However, 1.2.3 launches and your 2.0.1 crashes on launch. I've attached the crash log it generated.

[210311_vintel-201-mac-crash.txt](https://github.com/Xanthos-Code/vintel/files/6125410/210311_vintel-201-mac-crash.txt)

**Comment by Eingang** [comment]
> I appreciate that there's a Mac version! I've been using 1.2.3 for ages. However, 1.2.3 launches and your 2.0.1 crashes on launch. I've attached the crash log it generated.
> 
> [210311_vintel-201-mac-crash.txt](https://github.com/Xanthos-Code/vintel/files/6125410/210311_vintel-201-mac-crash.txt)

I just looked inside the package. It doesn't look to me like it's packaged correctly. Instead of having a `Contents` folder inside the application package and that then having Frameworks, MacOS, and Resources folders along with the Info.plist file, 2.0.1 `vintel.app` contains some kind of `vintel.app` binary file and an empty `vintel` folder. The binary is 68 MB compared to the 1.2.3 one of 28 MB.

If I have time, I'll try mucking around to create one in the correct structure and see if that works. I'm not going to try to compile from scratch. That was painful last time I tried it. :-o

**Comment by jblemee** [comment]
clean up

**Pull request closed without merging**
